name: yokapos
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.5
  esc_pos_utils_plus: ^2.0.3
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.0
  freezed_annotation: ^2.4.1
  get_it: ^8.2.0
  go_router: ^12.1.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  injectable: ^2.3.2
  intl: ^0.20.2
  json_annotation: ^4.8.1
  mobile_scanner: ^7.0.1
  open_filex: ^4.7.0
  package_info_plus: ^8.3.1
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.11.3
  percent_indicator: ^4.2.4
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  print_bluetooth_thermal: ^1.1.6
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  talker_dio_logger: ^4.9.3
  talker_flutter: ^4.9.3
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0

  # Code Generation
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/fonts/
    - assets/icons/
    - assets/icons/logo/
    - assets/images/
    - assets/images/logo/
